[env]
GODOT4_BIN = { value = "../../tools/godot/Godot_v4.3-stable_win64.exe", relative = true }

[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-args=-pthread",
    "-C", "target-feature=+atomics",
    "-C", "link-args=-sSIDE_MODULE=2",
    "-C", "panic=abort",
    "-Zlink-native-libraries=no",
    "-Cllvm-args=-enable-emscripten-cxx-exceptions=0",
]
